export const FETCHED_SEARCH = "FETCHED_SEARCH";
export const FETCHED_MOVIE_DETAILS = "FETCHED_MOVIE_DETAILS";

export const ADDED_TO_WATCHLIST = "ADDED_TO_WATCHLIST";
export const DELETED_FROM_WATCHLIST = "DELETED_FROM_WATCHLIST";
export const FETCHED_USER_WATCHLIST = "FETCHED_USER_WATCHLIST";

export const TOGGLED_NAV = "TOGGLED_NAV";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const UI_LOADING_INIT = "UI_LOADING_INIT";
export const UI_LOADING_COMPLETE = "UI_LOADING_COMPLETE";
